
# .streamlit/secrets.toml

# Example for OpenAI
OPENAI_API_KEY = "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"

# Example for another service
# MY_IMAGE_API_KEY = "abc-123-your-key-here"
